version: '3.2'

services:
  reverse-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'reverse-proxy-hr365'
    ports:
      - '${PORT}:80'
    volumes:
      - './proxy/vhosts:/etc/nginx/vhost.d'
      - './proxy/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './proxy/certs:/etc/nginx/certs'

  # прокси для пхп
  php-proxy:
    image: nginx
    container_name: "php-proxy-hr365"
    volumes:
      - './php/proxy/conf:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${BACKEND}"
    links:
      - php
    volumes_from:
      - php

  php:
    container_name: "php-hr365"
    build:
       context: ./php/
    volumes:
      - '../backend:/var/www/html'

  mysql:
    image: mysql:5.7
    container_name: "mysql-hr365"
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

### тут происходит подгрузка зависимостей для бека и фронта
  php-cli:
    container_name: "php-cli-hr365"
    build:
      context: ./php/
    volumes:
      - "../backend:/var/www/html"
    command: bash -c  "${BACKEND_DEPLOY_SCRIPT}"
    depends_on:
      - mysql


  ## Статика админ панели (в будущем)
